### ISSUE TITLE
Obsolete macro `map-put`

### ISSUE THREAD

**Issue by dschrempf** [DamienCassou/khardel#3]
On newer versions of Emacs, I get the following warning:
```
path/to/khardel.el: Warning: ‘map-put’ is an obsolete macro (as of 27.1); use map-put! or (setf (map-elt ...) ...) instead
```

Thanks for providing `khardel.el`!

**Comment by DamienCassou** [comment]
Thank you for the report. Fixed by https://gitea.petton.fr/DamienCassou/khardel/pulls/4.
